export const MAX_STANCE_BONUS = 2;
export const NEUTRAL_COMBAT_VALUE = 0;
export const NO_DAMAGE = 0;
export const NO_PENALTY = 0;
export const ICE_COMBAT_PENALTY = -2;
export const MILLISECONDS_PER_SECOND = 1000;
export const MINIMUM_COUNTDOWN_SECONDS = 0;
export const COMBAT_DICE_ROLL_FRAME_INTERVAL_MS = 80;
export const COMBAT_DICE_ROLL_DURATION_MS = 1000;
export const COMBAT_ATTACK_POSE_DURATION_MS = 900;
export const COMBAT_HIT_REACTION_DURATION_MS = 280;
export const COMBAT_OUTCOME_RESOLUTION_GRACE_MS = 500;
export const COMBAT_END_DEAD_FRAME_MS = 1000;
export const COMBAT_END_LINGER_MS = 1000;
export const COMBAT_ROUND_RESOLUTION_DURATION_MS =
	COMBAT_DICE_ROLL_DURATION_MS + COMBAT_ATTACK_POSE_DURATION_MS + COMBAT_HIT_REACTION_DURATION_MS;